[tool.poetry]
name = "gpwebpay"
version = "0.1.0"
description = "GPWebPay Gateway access with python"
authors = ["Filipa Andrade <filipa.andrade@gmail.com>"]

[tool.poetry.dependencies]
python = ">3.7"
cryptography="2.8"
requests="2.23"
flask = "^1.1.2"
python-dotenv = "^0.13.0"

[tool.poetry.dev-dependencies]
black = "19.10b0"
flake8 = "^3.8.1"
pylint = "^2.5.3"
pytest = "5.4.1"
pytest-cov = "^2.9.0"
responses = "^0.10.12"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
