[tool.poetry]
name = "gpwebpay"
version = "0.1.0"
description = "GPWebPay Gateway access with python"
authors = ["Filipa Andrade <filipa.andrade@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
