# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install poetry
      uses: dschep/install-poetry-action@v1.3
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      env:
        GPWEBPAY_MERCHANT_ID: ${{ secrets.GPWEBPAY_MERCHANT_ID }}
        GPWEBPAY_MERCHANT_PRIVATE_KEY: ${{ secrets.GPWEBPAY_MERCHANT_PRIVATE_KEY }}
        GPWEBPAY_MERCHANT_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPWEBPAY_MERCHANT_PRIVATE_KEY_PASSPHRASE }}
        GPWEBPAY_PUBLIC_KEY: ${{ secrets.GPWEBPAY_PUBLIC_KEY }}
      run: |
        pytest
