name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      uses: snok/install-poetry@v1.7.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      env:
        GPWEBPAY_MERCHANT_ID: ${{ secrets.GPWEBPAY_MERCHANT_ID }}
        GPWEBPAY_MERCHANT_PRIVATE_KEY: ${{ secrets.GPWEBPAY_MERCHANT_PRIVATE_KEY }}
        GPWEBPAY_MERCHANT_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPWEBPAY_MERCHANT_PRIVATE_KEY_PASSPHRASE }}
        GPWEBPAY_PUBLIC_KEY: ${{ secrets.GPWEBPAY_PUBLIC_KEY }}
      run: |
        source .venv/bin/activate
        pytest
